export  const languages = [
    { 
        id:1,
        name:"HTML",
        backgroundColor:"#E2680F",
        color:"#F9F4DA",
        isGone:false
    },
    {
        id:2,
        name:"CSS",
        backgroundColor:"#328AF1",
        color:"#F9F4DA",
        isGone:false
    },
    {
        id:3,
        name:"Javascript",
        backgroundColor:"#F4EB13",
        color:"#1E1E1E",
        isGone:false
    },
    {
        id:4,
        name:"React",
        backgroundColor:"#2ED3E9",
        color:"#1E1E1E",
        isGone:false
    },
    {
        id:5,
        name:"Typescript",
        backgroundColor:"#298EC6",
        color:"#F9F4DA",
        isGone:false
    },
    {
        id:6,
        name:"Node.js",
        backgroundColor:"#599137",
        color:"#F9F4DA",
        isGone:false
    },
    {
        id:7,
        name:"Python",
        backgroundColor:"#FFD742",
        color:"#000000",
        isGone:false
    },
    {
        id:8,
        name:"Ruby",
        backgroundColor:"#D02B2B",
        color:"#F9F4DA",
        isGone:false
    },
    {
        id:9,
        name:"Assembly",
        backgroundColor:"#2D519F",
        color:"#F9F4DA",
        isGone:false
    }]
